#!/bin/sh
mkdir build
cd build
cmake -DAPR_BUILD_STATIC_LIB=ON -DAPR_BUILD_SHARED_LIB=ON -DAPR_BUILD_EXAMPLES=ON -DAPR_TESTS=ON -DAPR_USE_CUDA=OFF ..
cmake --build .

CTEST_OUTPUT_ON_FAILURE=1 ctest -V
